[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

[[plugins]]
package = "./plugins/keep-data-cache"

[[plugins]]
package = "netlify-plugin-chromium"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://speedlify.netlify.app"
  to = "https://www.speedlify.dev"
  status = 301
  force = true